name: Build and test
on:
  push:
  pull_request:
jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
          - os: ubuntu-latest
            java: 11
          - os: ubuntu-latest
            java: 17
          - os: ubuntu-latest
            java: 21
          - os: macos-latest
            java: 17
          - os: windows-latest
            java: 17
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    # TODO: Temporary fix for Windows (July 2025). See error message:
    # error STL1000: Unexpected compiler version, expected Clang 19.0.0 or newer
    - name: Setup Clang 19 (Windows only)
      if: runner.os == 'Windows'
      uses: egor-tensin/setup-clang@v1
      with:
        version: 19
        platform: x64
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
        cache: sbt
    - name: Setup sbt
      uses: sbt/setup-sbt@v1
    - name: Build
      run: make build
    - name: Test
      run: make test
    - name: Sample
      run: make test-sample
